// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=.js"
// @generated from file example.proto (package waypoint.module.example.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * ExampleStats is the snapshot this template module publishes on
 * waypoint.<rover-id>.module.example.stats. Replace it with whatever your
 * module actually reports. Nullable fields use `optional` so the dashboard can
 * render a first-class "N/A" instead of a sentinel zero.
 *
 * @generated from message waypoint.module.example.v1.ExampleStats
 */
export class ExampleStats extends Message<ExampleStats> {
  /**
   * @generated from field: google.protobuf.Timestamp t = 1;
   */
  t?: Timestamp;

  /**
   * @generated from field: int64 count = 2;
   */
  count = protoInt64.zero;

  /**
   * @generated from field: optional string message = 3;
   */
  message?: string;

  constructor(data?: PartialMessage<ExampleStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "waypoint.module.example.v1.ExampleStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "t", kind: "message", T: Timestamp },
    { no: 2, name: "count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExampleStats {
    return new ExampleStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExampleStats {
    return new ExampleStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExampleStats {
    return new ExampleStats().fromJsonString(jsonString, options);
  }

  static equals(a: ExampleStats | PlainMessage<ExampleStats> | undefined, b: ExampleStats | PlainMessage<ExampleStats> | undefined): boolean {
    return proto3.util.equals(ExampleStats, a, b);
  }
}

